# Generated by Django 5.1 on 2025-01-16 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 10, 6, 7, 817144, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
